# Generated by Django 3.2.7 on 2021-10-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HearingTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_ear_freq_500', models.NullBooleanField()),
                ('left_ear_freq_1000', models.NullBooleanField()),
                ('left_ear_freq_2000', models.NullBooleanField()),
                ('left_ear_freq_4000', models.NullBooleanField()),
                ('right_ear_freq_500', models.NullBooleanField()),
                ('right_ear_freq_1000', models.NullBooleanField()),
                ('right_ear_freq_2000', models.NullBooleanField()),
                ('right_ear_freq_4000', models.NullBooleanField()),
            ],
        ),
    ]
