# Generated by Django 3.2.7 on 2021-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lne", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hearingtestdata", name="left_ear_freq_1000",
        ),
        migrations.RemoveField(
            model_name="hearingtestdata", name="left_ear_freq_2000",
        ),
        migrations.RemoveField(
            model_name="hearingtestdata", name="left_ear_freq_4000",
        ),
        migrations.RemoveField(model_name="hearingtestdata", name="left_ear_freq_500",),
        migrations.RemoveField(
            model_name="hearingtestdata", name="right_ear_freq_1000",
        ),
        migrations.RemoveField(
            model_name="hearingtestdata", name="right_ear_freq_2000",
        ),
        migrations.RemoveField(
            model_name="hearingtestdata", name="right_ear_freq_4000",
        ),
        migrations.RemoveField(
            model_name="hearingtestdata", name="right_ear_freq_500",
        ),
        migrations.AddField(
            model_name="hearingtestdata",
            name="left_ear_freq",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="hearingtestdata",
            name="right_ear_freq",
            field=models.BooleanField(null=True),
        ),
    ]
