# Generated by Django 3.2.7 on 2021-10-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lne", "0003_auto_20211018_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hearingtestdata",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lne.member",
            ),
        ),
    ]
