# Generated by Django 3.2.7 on 2021-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lne", "0004_alter_hearingtestdata_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("nationalid", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=12)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("complain", "Complain"),
                            ("suggestion", "Suggestion"),
                            ("asking", "Asking"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("dependants", "Dependants"),
                            ("covid", "Covid"),
                            ("sick leave", "Sick Leave"),
                            ("medication", "Medication"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
