# Generated by Django 3.2.7 on 2021-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lne", "0006_auto_20211018_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="description",
            field=models.TextField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="nationalid",
            field=models.CharField(max_length=10, verbose_name="National ID"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.CharField(max_length=13, verbose_name="Mobile Number"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complain", "Complain"),
                    ("suggestion", "Suggestion"),
                    ("asking", "Asking"),
                ],
                max_length=20,
                null=True,
                verbose_name="Reason",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="service",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("dependants", "Dependants"),
                    ("covid", "Covid"),
                    ("sick leave", "Sick Leave"),
                    ("medication", "Medication"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Service",
            ),
        ),
    ]
