# Generated by Django 3.2.7 on 2021-11-17 08:51

from django.db import migrations


CITIES = [
    {"name": "Cairo", "long": 23.545345345, "lat": 43.5305053053},
    {"name": "Riyad", "long": 26.45345, "lat": 66.053053},
    {"name": "Makka", "long": 99.65645, "lat": 55.05696},
    {"name": "Dammam", "long": 77.65645345, "lat": 11.5053053},
    {"name": "Gadda", "long": 44.345345, "lat": 77.5053053},
]


def forward(apps, schema_editor):
    City = apps.get_model("lne", "City")

    for city in CITIES:
        City.objects.filter(name=city["name"]).update(
            long=city["long"], lat=city["lat"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lne", "0013_populate_cities"),
    ]

    operations = [migrations.RunPython(forward)]
