# Generated by Django 3.2.7 on 2021-11-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lne", "0014_auto_20211117_1158"),
        ("lne", "0014_update_long_lat"),
    ]

    operations = []
