# Generated by Django 3.2.7 on 2021-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterclass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="has_offer",
            field=models.BooleanField(default=False),
        ),
    ]
