# Generated by Django 3.2.7 on 2021-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0002_book_has_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=False, upload_to='photos/'),
        ),
    ]
