# Generated by Django 3.2.7 on 2021-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="teacher",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
