# Generated by Django 3.2.7 on 2021-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_student_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="level",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("midlevel", "Mid Level"),
                    ("expert", "Expert"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
