# Generated by Django 3.2.7 on 2021-09-28 11:36

from django.db import migrations

import apps.core.fields.names


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_teacher_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name_ar",
            field=apps.core.fields.names.ArabicNameField(
                blank=True, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="name_en",
            field=apps.core.fields.names.ArabicNameField(
                blank=True, max_length=256, null=True
            ),
        ),
    ]
