# Generated by Django 3.2.7 on 2021-09-28 12:07

import apps.core.fields.general
import apps.core.fields.names
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210928_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="age", field=apps.core.fields.general.AgeField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="name_en",
            field=apps.core.fields.names.EnglishNameField(
                blank=True, max_length=256, null=True
            ),
        ),
    ]
