# Generated by Django 3.2.7 on 2021-10-02 06:21

import apps.core.fields.general
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=apps.core.fields.general.AgeField(blank=True, null=True),
        ),
    ]
