# Generated by Django 3.2.7 on 2021-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
