# Generated by Django 3.2.7 on 2021-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="has_offer",
            field=models.BooleanField(default=False),
        ),
    ]
