# Generated by Django 3.2.7 on 2021-10-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_category_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Not Specified')], default='n', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quizzes', to='core.category'),
        ),
    ]
