# Generated by Django 3.2.7 on 2021-10-09 10:17

import apps.core.mixins.db
import apps.core.validators.base_validation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_author_timestampmodelmixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='national_id',
            field=apps.core.mixins.db.NationalIDField(default='e.g. 012-345678-9', max_length=14, validators=[apps.core.validators.base_validation.NationalIDValidator]),
        ),
    ]
