# Generated by Django 3.2.7 on 2021-10-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_author_national_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Of Birth{"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
