# Generated by Django 3.2.7 on 2021-10-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_author_national_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name="basicprofile", options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="TechLead",
            fields=[
                (
                    "developer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.developer",
                    ),
                ),
                ("senior_exp", models.SmallIntegerField()),
            ],
            bases=("core.developer",),
        ),
    ]
