# Generated by Django 3.2.7 on 2021-10-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20211009_2042"),
    ]

    operations = [
        migrations.CreateModel(
            name="ISBN",
            fields=[
                (
                    "book_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.book",
                    ),
                ),
                ("isb", models.TextField(max_length=256, verbose_name="ISBN")),
            ],
            bases=("core.book",),
        ),
        migrations.AlterModelOptions(name="developer", options={"ordering": ["id"]},),
    ]
