# Generated by Django 3.2.7 on 2021-10-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_auto_20211009_2123"),
    ]

    operations = [
        migrations.RenameField(model_name="isbn", old_name="isb", new_name="isbnum",),
    ]
