# Generated by Django 3.2.7 on 2021-10-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_rename_isb_isbn_isbnum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Iphone",
            fields=[
                (
                    "mobile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.mobile",
                    ),
                ),
                ("iface", models.BooleanField(default=True)),
            ],
        ),
    ]
