# Generated by Django 3.2.7 on 2021-10-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_iphone_mobile"),
    ]

    operations = [
        migrations.DeleteModel(name="Iphone",),
    ]
