# Generated by Django 3.2.7 on 2021-10-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20211009_2233"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlugModelMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="medicalitemexport", options={"ordering": ["id"]},
        ),
    ]
