# Generated by Django 3.2.7 on 2021-10-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteBook",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.product",
                    ),
                ),
                ("pages", models.PositiveSmallIntegerField()),
            ],
            options={"abstract": False,},
            bases=("core.product",),
        ),
    ]
