# Generated by Django 3.2.7 on 2021-10-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_notebook"),
    ]

    operations = [
        migrations.CreateModel(
            name="TLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("m", "Male"),
                            ("f", "Female"),
                            ("n", "Not Specified"),
                        ],
                        default="n",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Of Birth"
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("team_numbers", models.PositiveSmallIntegerField()),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created"],
                "verbose_name": "Single Product",
                "verbose_name_plural": "Store Products",
            },
        ),
    ]
