# Generated by Django 3.2.7 on 2021-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last modified datetime')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Available')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
