# Generated by Django 3.2.7 on 2021-10-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
    ]
