# Generated by Django 3.2.7 on 2021-10-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
